
---
name: Security Check
on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  Security_Check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Phase
        run: |
          echo Entering install phase..
          brew install tfsec
          tfsec --version

          tfsec .
